const $=id=>document.getElementById(id); let vehicles=[], imageUrl='';
const key=()=>sessionStorage.getItem('irAdminKey')||'';
async function api(url,opt={}){opt.headers={...(opt.headers||{}),'X-Admin-Key':key()};const r=await fetch(url,opt);if(!r.ok)throw new Error((await r.text())||'Errore server');return r.status===204?null:r.json()}
async function load(){try{vehicles=await api('/api/vehicles?all=1');$('adminStatus').textContent='Catalogo connesso';$('adminStatus').className='ok';render()}catch(e){$('adminStatus').textContent='Accesso non riuscito';$('adminStatus').className='bad';$('adminVehicles').innerHTML='<p>Verifica la chiave amministratore e la configurazione Cloudflare.</p>'}}
$('connectAdmin').onclick=()=>{sessionStorage.setItem('irAdminKey',$('adminKey').value);load()};$('refreshVehicles').onclick=load;
function render(){$('adminVehicles').innerHTML=vehicles.length?vehicles.map(v=>`<article class="admin-car"><img src="${v.image_url||'assets/logo-symbol.png'}"><div><b>${v.name}</b><span>${v.year||'-'} • ${Number(v.km||0).toLocaleString('it-IT')} km • ${v.fuel} • ${v.gear}</span><span>${v.for_rent?'Noleggio € '+(v.rent_price||0)+'/giorno':''} ${v.for_sale?'• Vendita € '+Number(v.sale_price||0).toLocaleString('it-IT'):''}</span><small>${v.status}</small></div><div class="admin-actions"><button onclick="editV(${v.id})">Modifica</button><button class="danger" onclick="delV(${v.id})">Elimina</button></div></article>`).join(''):'<p>Nessun veicolo pubblicato.</p>'}
$('vehicleImage').onchange=e=>{const f=e.target.files[0];if(!f)return;imageUrl=URL.createObjectURL(f);$('imagePreview').src=imageUrl;$('imagePreview').hidden=false};
$('vehicleAdminForm').onsubmit=async e=>{e.preventDefault();try{let uploaded='';const f=$('vehicleImage').files[0];if(f){const fd=new FormData();fd.append('image',f);const u=await api('/api/upload',{method:'POST',body:fd});uploaded=u.url}const id=$('vehicleId').value;const old=vehicles.find(v=>String(v.id)===String(id))||{};const body={name:$('vehicleName').value.trim(),type:$('vehicleType').value,year:+$('vehicleYear').value||0,km:+$('vehicleKm').value||0,fuel:$('vehicleFuel').value,gear:$('vehicleGear').value,seats:+$('vehicleSeats').value||5,for_rent:$('forRent').checked,for_sale:$('forSale').checked,featured:$('featured').checked,rent_price:+$('rentPrice').value||0,sale_price:+$('salePrice').value||0,status:$('vehicleStatus').value,description:$('vehicleDesc').value.trim(),image_url:uploaded||old.image_url||''};await api(id?`/api/vehicles?id=${id}`:'/api/vehicles',{method:id?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});reset();await load();alert('Veicolo salvato e pubblicato.')}catch(err){alert(err.message)}};
function reset(){$('vehicleAdminForm').reset();$('vehicleId').value='';$('imagePreview').hidden=true;imageUrl='';$('forRent').checked=true}$('resetVehicle').onclick=reset;
window.editV=id=>{const v=vehicles.find(x=>x.id===id);if(!v)return;$('vehicleId').value=v.id;$('vehicleName').value=v.name;$('vehicleType').value=v.type;$('vehicleYear').value=v.year;$('vehicleKm').value=v.km;$('vehicleFuel').value=v.fuel;$('vehicleGear').value=v.gear;$('vehicleSeats').value=v.seats;$('forRent').checked=!!v.for_rent;$('forSale').checked=!!v.for_sale;$('featured').checked=!!v.featured;$('rentPrice').value=v.rent_price||'';$('salePrice').value=v.sale_price||'';$('vehicleStatus').value=v.status;$('vehicleDesc').value=v.description||'';if(v.image_url){$('imagePreview').src=v.image_url;$('imagePreview').hidden=false}scrollTo({top:0,behavior:'smooth'})};
window.delV=async id=>{if(confirm('Eliminare questo veicolo dal catalogo?')){try{await api(`/api/vehicles?id=${id}`,{method:'DELETE'});load()}catch(e){alert(e.message)}}};
