
const dict={en:{'Home':'Home','Noleggio Auto':'Car Rental','Auto in vendita':'Cars for Sale','Servizi':'Services','Le nostre sedi':'Our Locations','Assistenza H24':'24/7 Assistance','Chi siamo':'About Us','Contatti':'Contact','Altri noleggi':'Other Rentals','La tua prossima strada comincia qui.':'Your next road starts here.','Noleggio e vendita auto. Soluzioni semplici, sicure e su misura per ogni esigenza di mobilità.':'Car rental and sales. Simple, safe, tailored mobility solutions.','Noleggia un’auto':'Rent a car','Trova la tua auto':'Find your car','Sempre al tuo fianco':'Always by your side','Scopri Italy Rent':'Discover Italy Rent','Cosa facciamo':'What we do'},it:{}};
let lang=localStorage.getItem('irlang')||'it';function applyLang(){document.documentElement.lang=lang;document.querySelectorAll('[data-i18n]').forEach(el=>{let k=el.dataset.i18n;if(!el.dataset.it)el.dataset.it=el.textContent;if(lang==='en'&&dict.en[k])el.textContent=dict.en[k];else el.textContent=el.dataset.it});document.querySelectorAll('.lang').forEach(b=>b.textContent=lang.toUpperCase())}document.querySelectorAll('.lang').forEach(b=>b.onclick=()=>{lang=lang==='it'?'en':'it';localStorage.setItem('irlang',lang);applyLang()});applyLang();
document.querySelectorAll('.carpic img').forEach(img=>img.onerror=()=>{img.classList.add('broken');let f=img.nextElementSibling;if(f)f.style.display='flex'});
const answers={noleggio:'Puoi scegliere sede, date e categoria nella pagina Noleggio Auto e simulare la prenotazione.',vendita:'Nella pagina Auto in vendita trovi 10 vetture demo con prezzi fittizi e richiesta informazioni.',documenti:'Per la demo: patente valida, documento di identità e metodo di pagamento. Le condizioni reali saranno definite da Italy Rent.',h24:'Per assistenza H24 chiama il centralino 081 192 99090. La pagina Assistenza spiega il percorso dedicato.',sedi:'Italy Rent è presente nelle 8 sedi demo indicate: Bolzano, Parma, Lido di Camaiore, Roma, Napoli Volla, Napoli Pollena Trocchia, Napoli Somma Vesuviana e Foggia.',operatore:'Puoi chiamare il centralino 081 192 99090 oppure utilizzare WhatsApp al 333 534 8113.'};
const chat=document.getElementById('chat'),messages=document.getElementById('messages');if(chat){document.getElementById('gioiaBtn').onclick=()=>chat.classList.toggle('open');document.getElementById('closeChat').onclick=()=>chat.classList.remove('open');document.querySelectorAll('.quick button').forEach(b=>b.onclick=()=>reply(b.textContent,answers[b.dataset.q]));document.getElementById('chatForm').onsubmit=e=>{e.preventDefault();let i=document.getElementById('chatInput'),q=i.value.trim();if(!q)return;let l=q.toLowerCase(),a=l.includes('vend')||l.includes('acquist')?answers.vendita:l.includes('document')?answers.documenti:l.includes('assist')||l.includes('h24')?answers.h24:l.includes('sede')?answers.sedi:l.includes('operat')||l.includes('telefono')?answers.operatore:answers.noleggio;reply(q,a);i.value=''};}function reply(q,a){messages.innerHTML+=`<div class="user">${q}</div><div class="bot">${a}</div>`;messages.scrollTop=messages.scrollHeight}

// V2.0 mobile menu
document.querySelectorAll('.menu-toggle').forEach(btn=>{btn.addEventListener('click',()=>{const nav=btn.parentElement.querySelector('.main-nav');const open=nav.classList.toggle('open');btn.setAttribute('aria-expanded',open?'true':'false')})});

const fullTranslations={
'ITALY RENT • MOBILITÀ SENZA PENSIERI':'ITALY RENT • WORRY-FREE MOBILITY','Sede':'Location','Ritiro':'Pick-up','Riconsegna':'Return','Categoria':'Category','Tutte':'All','Cerca auto':'Search cars','Mobilità costruita intorno alle persone':'Mobility built around people','I servizi Italy Rent':'Italy Rent services','Noleggio e vendita':'Rental and sales','Vedi tutte le auto →':'View all cars →','ALTRE SOLUZIONI':'OTHER SOLUTIONS','Quando l’auto non basta':'When a car is not enough','Moto':'Scooters','Imbarcazioni':'Boats','Mezzi da lavoro':'Work equipment','Noleggio moto e scooter per spostamenti, turismo e mobilità agile.':'Scooter and motorcycle rental for travel, tourism and agile mobility.','Soluzioni demo per il noleggio di imbarcazioni e attività sul mare.':'Demo solutions for boat rental and activities at sea.','Veicoli e attrezzature per professionisti, cantieri e necessità operative.':'Vehicles and equipment for professionals, construction sites and operational needs.','Dettagli':'Details','Prenota':'Book','Richiedi':'Enquire','Noleggio':'Rental','Vendita':'Sale','AUTO IN EVIDENZA':'FEATURED CARS','Scopri Italy Rent':'Discover Italy Rent','Cosa facciamo':'What we do','Conosci l’azienda →':'About the company →','DEMO • prezzi e disponibilità fittizi':'DEMO • fictional prices and availability','Più possibilità, quando servono':'More options, when you need them','ALTRE TIPOLOGIE DI NOLEGGIO':'OTHER RENTAL TYPES','Moto e scooter':'Scooters and motorcycles','Richiedi disponibilità':'Check availability','Richiedi informazioni':'Request information','Parla con un consulente':'Talk to an advisor','Scrivi la tua domanda...':'Type your question...','Acquisto':'Purchase','Documenti':'Documents','Sedi':'Locations','Operatore':'Operator','Online • Posso aiutarti?':'Online • Can I help?','Assistente virtuale Italy Rent':'Italy Rent virtual assistant'};
const originalTexts=new WeakMap();function translateTree(){document.querySelectorAll('body *').forEach(el=>{if(el.children.length===0){let t=el.textContent.trim();if(!t)return;if(!originalTexts.has(el))originalTexts.set(el,t);let it=originalTexts.get(el);if(lang==='en'&&fullTranslations[it])el.textContent=fullTranslations[it];else if(lang==='it')el.textContent=it;}if(el.tagName==='INPUT'&&el.placeholder){if(!el.dataset.itPlaceholder)el.dataset.itPlaceholder=el.placeholder;if(lang==='en'&&fullTranslations[el.dataset.itPlaceholder])el.placeholder=fullTranslations[el.dataset.itPlaceholder];else if(lang==='it')el.placeholder=el.dataset.itPlaceholder;}})}
const baseApplyLang=applyLang;applyLang=function(){baseApplyLang();translateTree()};document.querySelectorAll('.lang').forEach(b=>b.onclick=()=>{lang=lang==='it'?'en':'it';localStorage.setItem('irlang',lang);applyLang()});applyLang();
