// V2.1 — bilingual IT/EN. The original Italian text is kept in the HTML;
// this dictionary switches all principal visible interface/content text to English.
const EN = {
'Home':'Home','Noleggio Auto':'Car Rental','Auto in vendita':'Cars for Sale','Servizi':'Services','Le nostre sedi':'Our Locations','Assistenza H24':'24/7 Assistance','Chi siamo':'About Us','Contatti':'Contact','Altri noleggi':'Other Rentals',
'AUTO • NOLEGGIO • VENDITA':'CARS • RENTAL • SALES','PRENOTAZIONE DEMO':'DEMO BOOKING','Configura il tuo noleggio':'Configure your rental','Veicolo':'Vehicle','Scegli l’auto dal catalogo.':'Choose a car from the catalogue.','Sede e date':'Location and dates','Imposta ritiro e riconsegna.':'Set pick-up and return.','Extra':'Extras','Aggiungi servizi e preferenze.':'Add services and preferences.','Riepilogo':'Summary','Invia la richiesta dimostrativa.':'Send the demo request.',
'Demo interattiva • veicoli, prezzi e disponibilità a scopo dimostrativo.':'Interactive demo • vehicles, prices and availability are for demonstration only.','Online • Posso aiutarti?':'Online • Can I help?','Assistente virtuale Italy Rent':'Italy Rent virtual assistant','Noleggio':'Rental','Acquisto':'Purchase','Documenti':'Documents','Sedi':'Locations','Operatore':'Operator','Scrivi la tua domanda...':'Type your question...',
'CHI SIAMO':'ABOUT US','Mobilità, noleggio e vendita':'Mobility, rental and sales','Italy Rent è una realtà dedicata alla mobilità, con un’offerta concentrata sul noleggio e sulla vendita di automobili e una rete di sedi distribuite in diverse aree d’Italia.':'Italy Rent is a mobility company focused on car rental and sales, with a network of locations across several areas of Italy.','L’obiettivo è offrire al cliente un unico riferimento per scegliere il veicolo più adatto, ricevere informazioni chiare, accedere ai servizi di assistenza e valutare soluzioni personalizzate.':'Our goal is to give customers one point of contact to choose the right vehicle, receive clear information, access assistance and evaluate tailored solutions.','Accanto al settore auto, l’offerta può comprendere anche moto, imbarcazioni e mezzi da lavoro, organizzati in sezioni dedicate.':'Alongside cars, the offer may also include motorcycles, boats and work equipment, organised in dedicated sections.','Il nostro approccio':'Our approach','Centralità del cliente':'Customer focus','Scelta ampia e diversificata':'Wide and diversified choice','Presenza sul territorio':'Local presence','Soluzioni per privati e aziende':'Solutions for individuals and businesses','Processi digitali semplici e trasparenti':'Simple and transparent digital processes','Testo istituzionale dimostrativo da validare con l’azienda prima della pubblicazione finale.':'Demo corporate text to be validated with the company before final publication.',
'NOLEGGIO AUTO':'CAR RENTAL','Scegli la tua auto':'Choose your car','Dalla City Car al van: 10 proposte dimostrative per mostrare al cliente come funzionerà il catalogo reale.':'From city cars to vans: 10 demo vehicles showing how the real catalogue will work.','Ritiro':'Pick-up','Riconsegna':'Return','Tutte':'All','Cerca auto':'Search cars','• fotografie reali del modello • prezzi e disponibilità fittizi':'• real model photos • fictional prices and availability','Dettagli':'Details','Prenota':'Book',
'AUTO IN VENDITA':'CARS FOR SALE','Trova la tua prossima auto':'Find your next car','10 vetture demo con prezzi chiaramente fittizi. Nel sito definitivo il catalogo potrà essere aggiornato con disponibilità, fotografie e dati reali.':'10 demo cars with clearly fictional prices. In the final site, the catalogue can be updated with real availability, photos and data.','Marca o modello':'Make or model','Nessun limite':'No limit','Filtra':'Filter','Vendita':'Sale','Richiedi':'Enquire','Tutti i prezzi, chilometraggi e disponibilità presenti in questa demo sono fittizi e non costituiscono offerta commerciale.':'All prices, mileage and availability shown in this demo are fictional and do not constitute a commercial offer.',
'CONTATTI':'CONTACT','Parliamo della tua esigenza':'Tell us what you need','Mobilità, noleggio e vendita auto con una rete di sedi e assistenza dedicata.':'Mobility, car rental and sales with a network of locations and dedicated assistance.','Sede legale':'Registered office','Telefoni':'Phone numbers','Assistenza':'Assistance','Servizio H24 dedicato ai clienti con noleggio attivo.':'24/7 service dedicated to customers with an active rental.','Nome e cognome':'Full name','Azienda':'Company','Telefono':'Phone','Noleggio auto':'Car rental','Acquisto auto':'Car purchase','Informazioni sede':'Location information','Soluzione personalizzata':'Tailored solution','Messaggio':'Message','Accetto il trattamento dei dati per la gestione della richiesta (demo).':'I agree to the processing of data to manage this request (demo).','Invia richiesta':'Send request',
'ITALY RENT • MOBILITÀ SENZA PENSIERI':'ITALY RENT • WORRY-FREE MOBILITY','La tua prossima strada comincia qui.':'Your next road starts here.','Noleggio e vendita auto. Soluzioni semplici, sicure e su misura per ogni esigenza di mobilità.':'Car rental and sales. Simple, safe and tailored solutions for every mobility need.','Noleggia un’auto':'Rent a car','Trova la tua auto':'Find your car','✓ Assistenza H24':'✓ 24/7 Assistance','✓ 8 sedi':'✓ 8 locations','✓ Supporto dedicato':'✓ Dedicated support','Scopri Italy Rent':'Discover Italy Rent','Mobilità costruita intorno alle persone':'Mobility built around people','Conosci l’azienda →':'About the company →','Cosa facciamo':'What we do','I servizi Italy Rent':'Italy Rent services','Noleggio auto per diverse esigenze e durate':'Car rental for different needs and durations','Vendita auto nuove, usate e km 0 (demo)':'New, used and pre-registered car sales (demo)','Assistenza H24 durante il noleggio':'24/7 assistance during the rental','Soluzioni personalizzate per aziende e professionisti':'Tailored solutions for businesses and professionals','Finanziamenti: sezione predisposta per il futuro':'Financing: section prepared for future use','Altri noleggi: moto, imbarcazioni e mezzi da lavoro':'Other rentals: motorcycles, boats and work equipment','AUTO IN EVIDENZA':'FEATURED CARS','Noleggio e vendita':'Rental and sales','Vedi tutte le auto →':'View all cars →','ALTRE SOLUZIONI':'OTHER SOLUTIONS','Quando l’auto non basta':'When a car is not enough','Moto':'Scooters','Noleggio moto e scooter per spostamenti, turismo e mobilità agile.':'Scooter and motorcycle rental for travel, tourism and agile mobility.','Imbarcazioni':'Boats','Soluzioni demo per il noleggio di imbarcazioni e attività sul mare.':'Demo solutions for boat rental and activities at sea.','Mezzi da lavoro':'Work equipment','Veicoli e attrezzature per professionisti, cantieri e necessità operative.':'Vehicles and equipment for professionals, construction sites and operational needs.',
'SCHEDA VEICOLO':'VEHICLE DETAILS','Dettagli dell’auto':'Car details','Veicolo selezionato':'Selected vehicle','La scheda finale mostrerà fotografie, caratteristiche, dotazioni, alimentazione, cambio, posti, condizioni e disponibilità.':'The final vehicle page will show photos, specifications, equipment, fuel type, transmission, seats, conditions and availability.','Simula prenotazione':'Simulate booking','Incluso nella scheda':'Included in the vehicle page','Galleria fotografica':'Photo gallery','Caratteristiche tecniche':'Technical specifications','Dotazioni principali':'Main equipment','Condizioni economiche':'Pricing conditions','Richiesta informazioni':'Information request',
'ASSISTENZA H24':'24/7 ASSISTANCE','Sempre al tuo fianco, anche durante il viaggio':'Always by your side, even while travelling','Una pagina dedicata a chi ha già un noleggio attivo e necessita di supporto. Nella versione finale procedure e coperture saranno allineate ai servizi effettivamente offerti da Italy Rent.':'A page for customers with an active rental who need support. In the final version, procedures and coverage will reflect the services actually offered by Italy Rent.','☎ Chiama 081 913 1386':'☎ Call 081 913 1386','Gioia • Assistenza Italy Rent':'Gioia • Italy Rent Assistance','Supporto e primo orientamento H24':'24/7 support and initial guidance','Come richiedere assistenza':'How to request assistance','Contattaci':'Contact us','Chiama il centralino H24 e descrivi la necessità.':'Call the 24/7 switchboard and describe your need.','Identifica il noleggio':'Identify your rental','Tieni a disposizione contratto, targa e sede di ritiro.':'Have your contract, registration plate and pick-up location ready.','Ricevi indicazioni':'Receive instructions','L’operatore indica la procedura prevista per il caso specifico.':'The operator will explain the procedure for your specific case.','Segui l’assistenza':'Follow the assistance process','Il cliente viene accompagnato fino alla gestione della richiesta.':'The customer is supported through the handling of the request.','Guasto o fermo veicolo':'Breakdown or vehicle stop','Canale dedicato per segnalare problemi durante l’utilizzo.':'Dedicated channel for reporting problems during use.','Incidente o imprevisto':'Accident or unexpected event','Indicazioni immediate sui passaggi da seguire e sui riferimenti da contattare.':'Immediate guidance on the steps to follow and who to contact.','Altre necessità':'Other needs','Supporto per dubbi sul contratto, riconsegna o esigenze durante il viaggio.':'Support for questions about the contract, return or needs during the journey.',
'FINANZIAMENTI':'FINANCING','Una soluzione in preparazione':'A solution in development','Prossimamente':'Coming soon','La demo mostra lo spazio dedicato ai futuri strumenti di finanziamento: simulazione rata, anticipo, durata e richiesta di contatto. Nessun calcolo o finanziamento reale viene elaborato in questa versione.':'This demo shows the area reserved for future financing tools: instalment simulation, down payment, term and contact request. No real financing calculation is performed in this version.','Richiedi informazioni':'Request information',
'ALTRE TIPOLOGIE DI NOLEGGIO':'OTHER RENTAL TYPES','Più possibilità, quando servono':'More options, when you need them','L’automotive resta il cuore del sito. Qui presentiamo, in sezioni separate, le altre possibilità offerte da Italy Rent.':'Automotive remains the core of the site. Here we present Italy Rent’s other rental options in dedicated sections.','Moto e scooter':'Scooters and motorcycles','Catalogo demo per moto e scooter, con ricerca per sede, periodo e categoria. Ideale per mobilità urbana, turismo e spostamenti agili.':'Demo catalogue for scooters and motorcycles, searchable by location, period and category. Ideal for urban mobility, tourism and agile travel.','Richiedi disponibilità':'Check availability','Area dimostrativa per richieste di noleggio imbarcazioni, con informazioni sul periodo, località e tipologia desiderata.':'Demo area for boat rental enquiries, including period, location and preferred type.','Soluzioni per aziende e professionisti: veicoli commerciali, mezzi operativi e attrezzature in base alle esigenze del progetto.':'Solutions for businesses and professionals: commercial vehicles, work equipment and machinery based on project needs.','Parla con un consulente':'Talk to an advisor',
'SERVIZI':'SERVICES','Una soluzione per ogni esigenza':'A solution for every need','Ogni riquadro è navigabile e porta alla relativa area della demo.':'Each card is clickable and opens the relevant demo area.','Catalogo per categorie, ricerca per sede e date, scheda veicolo e simulazione di prenotazione.':'Catalogue by category, location and date search, vehicle page and booking simulation.','Scopri il servizio →':'Discover the service →','Vendita auto':'Car sales','Vetrina di auto nuove, usate e km 0 con filtri, prezzi, dettagli e richiesta informazioni.':'Showcase of new, used and pre-registered cars with filters, prices, details and enquiries.','Canale dedicato per esigenze durante il noleggio, guasti, incidenti e supporto al cliente.':'Dedicated channel for rental needs, breakdowns, accidents and customer support.','Finanziamenti':'Financing','Area predisposta per simulazione rata e richiesta finanziamento. Funzionalità reale da integrare successivamente.':'Area prepared for instalment simulation and financing requests. Real functionality to be integrated later.','8 sedi':'8 locations','Una rete di sedi da Bolzano a Foggia. Il centralino indirizza il cliente verso la sede desiderata.':'A network of locations from Bolzano to Foggia. The switchboard directs customers to the preferred location.','Soluzioni personalizzate':'Tailored solutions','Proposte su misura per aziende, professionisti, flotte, esigenze stagionali e richieste particolari.':'Tailored proposals for businesses, professionals, fleets, seasonal needs and special requests.',
'LE NOSTRE SEDI':'OUR LOCATIONS','Italy Rent sul territorio':'Italy Rent locations','Un unico contatto per tutte le sedi':'One contact for all locations','Chiama il centralino':'Call the switchboard','Punto Italy Rent • informazioni e disponibilità tramite centralino.':'Italy Rent location • information and availability via the switchboard.',
'DEMO • prezzi e disponibilità fittizi':'DEMO • fictional prices and availability'
};
let lang=localStorage.getItem('irlang')||'it';
const originals=new WeakMap();
function translatePage(){
 document.documentElement.lang=lang;
 document.querySelectorAll('body *').forEach(el=>{
   if(el.children.length===0){const current=el.textContent.trim(); if(!current)return; if(!originals.has(el)) originals.set(el,current); const it=originals.get(el); el.textContent=(lang==='en'&&EN[it])?EN[it]:it;}
   if((el.tagName==='INPUT'||el.tagName==='TEXTAREA')&&el.placeholder){if(!el.dataset.itPlaceholder)el.dataset.itPlaceholder=el.placeholder; const it=el.dataset.itPlaceholder; el.placeholder=(lang==='en'&&EN[it])?EN[it]:it;}
 });
 document.querySelectorAll('.lang').forEach(b=>{b.textContent=lang==='it'?'EN':'IT'; b.setAttribute('aria-label',lang==='it'?'Switch to English':'Passa all’italiano'); b.title=b.getAttribute('aria-label');});
}
document.querySelectorAll('.lang').forEach(b=>b.addEventListener('click',()=>{lang=lang==='it'?'en':'it';localStorage.setItem('irlang',lang);translatePage();}));
translatePage();

document.querySelectorAll('.carpic img').forEach(img=>img.onerror=()=>{img.classList.add('broken');let f=img.nextElementSibling;if(f)f.style.display='flex'});
const answers={noleggio:'Puoi scegliere sede, date e categoria nella pagina Noleggio Auto e simulare la prenotazione.',vendita:'Nella pagina Auto in vendita trovi 10 vetture demo con prezzi fittizi e richiesta informazioni.',documenti:'Per la demo: patente valida, documento di identità e metodo di pagamento. Le condizioni reali saranno definite da Italy Rent.',h24:'Per assistenza H24 chiama il centralino 081 913 1386. La pagina Assistenza spiega il percorso dedicato.',sedi:'Italy Rent è presente nelle 8 sedi demo indicate: Bolzano, Parma, Lido di Camaiore, Roma, Napoli Volla, Napoli Pollena Trocchia, Napoli Somma Vesuviana e Foggia.',operatore:'Puoi chiamare il centralino 081 913 1386 oppure utilizzare WhatsApp.'};
const chat=document.getElementById('chat'),messages=document.getElementById('messages');if(chat){document.getElementById('gioiaBtn').onclick=()=>chat.classList.toggle('open');document.getElementById('closeChat').onclick=()=>chat.classList.remove('open');document.querySelectorAll('.quick button').forEach(b=>b.onclick=()=>reply(b.textContent,answers[b.dataset.q]));document.getElementById('chatForm').onsubmit=e=>{e.preventDefault();let i=document.getElementById('chatInput'),q=i.value.trim();if(!q)return;let l=q.toLowerCase(),a=l.includes('vend')||l.includes('acquist')?answers.vendita:l.includes('document')?answers.documenti:l.includes('assist')||l.includes('h24')?answers.h24:l.includes('sede')?answers.sedi:l.includes('operat')||l.includes('telefono')?answers.operatore:answers.noleggio;reply(q,a);i.value=''};}function reply(q,a){messages.innerHTML+=`<div class="user">${q}</div><div class="bot">${a}</div>`;messages.scrollTop=messages.scrollHeight}

document.querySelectorAll('.menu-toggle').forEach(btn=>{btn.addEventListener('click',()=>{const nav=btn.parentElement.querySelector('.main-nav');const open=nav.classList.toggle('open');btn.setAttribute('aria-expanded',open?'true':'false')})});
